"use client";

import { useState } from "react";
import Link from "next/link";
import { Zap, LayoutDashboard, Users, Share2, Target, Sparkles, TrendingUp } from "lucide-react";
import type { Playbook } from "@/lib/types";
import { PlaybookOverview } from "./PlaybookOverview";
import { PlaybookICP } from "./PlaybookICP";
import { PlaybookChannels } from "./PlaybookChannels";
import { SharedWarmLeads } from "./SharedWarmLeads";
import { SharedPosts } from "./SharedPosts";
import { SharedGrowthHacks } from "./SharedGrowthHacks";

type Tab = "overview" | "icp" | "channels" | "posts" | "growth-hacks" | "leads";

const TABS: { id: Tab; label: string; Icon: React.ComponentType<{ className?: string }> }[] = [
  { id: "overview",      label: "Executive Summary",      Icon: LayoutDashboard },
  { id: "icp",           label: "Audience Profiling",     Icon: Users },
  { id: "channels",      label: "Distribution Channels",  Icon: Share2 },
  { id: "posts",         label: "Content Posts",          Icon: Sparkles },
  { id: "growth-hacks",  label: "Growth Hacks",           Icon: TrendingUp },
  { id: "leads",         label: "Warm Leads",             Icon: Target },
];

export function SharedPlaybookView({
  playbook,
  playbookId,
  shareToken,
}: {
  playbook: Playbook;
  playbookId: string;
  shareToken: string;
}) {
  const [activeTab, setActiveTab] = useState<Tab>("overview");

  return (
    <div className="min-h-screen bg-[#FAFAF7] text-slate-900">
      {/* Header */}
      <header className="sticky top-0 z-50 h-16 border-b border-[#E2E8F0] bg-white flex items-center px-6 justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#FF7A3D] to-[#F25C2C] flex items-center justify-center shadow-sm">
            <Zap className="w-4 h-4 text-white" strokeWidth={2.5} />
          </div>
          <Link
            href="/"
            className="text-[15px] font-semibold tracking-tight text-slate-900"
          >
            Get<span className="text-[#F25C2C]">Farcast</span>
          </Link>
          <span className="text-slate-300 hidden sm:block">/</span>
          <span className="text-[13px] text-slate-500 hidden sm:block">
            {playbook.productName} Playbook
          </span>
        </div>
        <Link
          href="/login"
          className="px-4 py-2 rounded-lg bg-gradient-to-r from-[#F25C2C] to-[#FF7A3D] text-white text-[12.5px] font-medium shadow-sm hover:shadow-md transition-all hover:-translate-y-0.5"
        >
          Get your own playbook →
        </Link>
      </header>

      {/* Tab bar */}
      <div className="sticky top-16 z-40 bg-white border-b border-[#E2E8F0]">
        <div className="flex overflow-x-auto px-6 scrollbar-none">
          {TABS.map(({ id, label, Icon }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id)}
              className={`flex items-center gap-2 px-4 py-3 text-[13px] font-medium whitespace-nowrap border-b-2 transition-colors -mb-px ${
                activeTab === id
                  ? "border-[#F25C2C] text-[#F25C2C]"
                  : "border-transparent text-slate-500 hover:text-slate-900"
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      <main className="max-w-[1200px] mx-auto px-6 py-8">
        <div className="bg-white rounded-3xl border border-[#E2E8F0] shadow-[0_1px_2px_rgba(15,23,42,0.04)] p-6 sm:p-8">
          {activeTab === "overview" && <PlaybookOverview playbook={playbook} />}
          {activeTab === "icp" && <PlaybookICP icp={playbook.icp} />}
          {activeTab === "channels" && (
            <PlaybookChannels playbookId={playbookId} channels={playbook.channels} />
          )}
          {activeTab === "posts" && <SharedPosts playbook={playbook} />}
          {activeTab === "growth-hacks" && (
            <SharedGrowthHacks shareToken={shareToken} />
          )}
          {activeTab === "leads" && <SharedWarmLeads shareToken={shareToken} />}
        </div>
      </main>

      <footer className="text-center py-8 text-[12px] text-slate-400">
        Generated by{" "}
        <Link href="/" className="text-[#F25C2C] font-medium hover:underline">
          GetFarcast
        </Link>{" "}
        · AI-powered growth playbooks
      </footer>
    </div>
  );
}
