import type { Metadata } from "next";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Privacy Policy — Farcast",
};

export default function PrivacyPage() {
  return (
    <main className="bg-[#faf8f6] text-[#1a1a2e] min-h-screen font-sans flex flex-col">
      <Navbar />

      <div className="flex-1 max-w-3xl mx-auto w-full px-6 pt-32 pb-24">
        <h1 className="text-4xl font-black mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-12">Last updated: 2024</p>

        <div className="prose prose-sm max-w-none space-y-8 text-gray-700">
          <p>
            Welcome to Farcast.
          </p>
          <p>
            Farcast ("us", "we", or "our") operates Farcast extension, available at{" "}
            <a href="https://chromewebstore.google.com/detail/bjobgelaoehgbnklgcaaehdpckmhkplk" className="text-[#ff6b4e] hover:underline break-all" target="_blank" rel="noopener noreferrer">
              https://chromewebstore.google.com/detail/bjobgelaoehgbnklgcaaehdpckmhkplk
            </a>{" "}
            (hereinafter referred to as "Service").
          </p>
          <p>
            Our Privacy Policy governs your usage of Farcast extension, and explains how we collect, safeguard and disclose information that results from your use of our Service.
          </p>
          <p>
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>
          <p>
            Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").
          </p>

          <Section title="1. Definitions">
            <p><strong>SERVICE</strong> means the Farcast extension (available at{" "}
              <a href="https://chromewebstore.google.com/detail/bjobgelaoehgbnklgcaaehdpckmhkplk" className="text-[#ff6b4e] hover:underline break-all" target="_blank" rel="noopener noreferrer">
                https://chromewebstore.google.com/detail/bjobgelaoehgbnklgcaaehdpckmhkplk
              </a>) website operated by Farcast's development team.
            </p>
            <p><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            <p><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
            <p><strong>DATA CONTROLLER</strong> means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
            <p><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
            <p><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</p>
            <p><strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
          </Section>

          <Section title="2. Information Collection and Use">
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
          </Section>

          <Section title="3. Type of Data Collected">
            <p><strong>Personal data</strong> — While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Email address</li>
              <li>Usage Data.</li>
            </ul>
          </Section>

          <Section title="4. Use of Data">
            <p>Farcast uses the collected data for various purposes:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>to provide and maintain our Service,</li>
              <li>to gather analysis or valuable information so that we can improve our Service;</li>
              <li>to monitor the usage of our Service;</li>
              <li>to detect, prevent and address technical issues;</li>
              <li>to fulfill any other purpose for which you provide it;</li>
              <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
              <li>in any other way we may describe when you provide the information;</li>
              <li>for any other purpose with your consent.</li>
            </ul>
          </Section>

          <Section title="5. Retention of Data">
            <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
          </Section>

          <Section title="6. Transfer of Data">
            <p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
            <p>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>
            <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>We will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
          </Section>

          <Section title="7. Disclosure of Data">
            <p>We may disclose personal information that we collect, or you provide:</p>
            <p className="font-semibold mt-4">(a) Disclosure for Law Enforcement.</p>
            <p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
            <p className="font-semibold mt-4">(b) Business Transaction.</p>
            <p>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p>
            <p className="font-semibold mt-4">(c) Other cases.</p>
            <p>We may disclose your information also:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>to contractors, service providers, and other third parties we use to support our business;</li>
              <li>to fulfill the purpose for which you provide it;</li>
              <li>for any other purpose disclosed by us when you provide the information;</li>
            </ul>
          </Section>

          <Section title="8. Security of Data">
            <p>The security of your data is important to us but remember that no method of transmission over the internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
          </Section>

          <Section title="9. Your Data Protection Rights Under General Data Protection Regulation (GDPR)">
            <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at{" "}
              <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" className="text-[#ff6b4e] hover:underline" target="_blank" rel="noopener noreferrer">https://eur-lex.europa.eu/eli/reg/2016/679/oj</a>
            </p>
            <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
            <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at{" "}
              <a href="mailto:farcast93@gmail.com" className="text-[#ff6b4e] hover:underline">farcast93@gmail.com</a>. In certain circumstances, you have the following data protection rights:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>the right to access, update or to delete the information we have on you;</li>
              <li>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
              <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
              <li>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
              <li>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
              <li>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;</li>
            </ul>
            <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide Service without some necessary data.</p>
            <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
          </Section>

          <Section title="10. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)">
            <p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on their website. – See more at:{" "}
              <a href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/" className="text-[#ff6b4e] hover:underline break-all" target="_blank" rel="noopener noreferrer">
                https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
              </a>
            </p>
            <p>According to CalOPPA we agree to the following:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>users can visit our site anonymously;</li>
              <li>our Privacy Policy link includes the word 'Privacy', and can easily be found on the page specified above on the home page of our website;</li>
              <li>users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
              <li>users are able to change their personal information by emailing us at{" "}
                <a href="mailto:farcast93@gmail.com" className="text-[#ff6b4e] hover:underline">farcast93@gmail.com</a>
              </li>
            </ul>
          </Section>

          <Section title="11. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)">
            <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:</p>

            <p className="font-semibold mt-4">(a) What personal information we have about you.</p>
            <p>If you make this request, we will return to you:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>The categories of personal information we have collected about you.</li>
              <li>The categories of sources from which we collect your personal information.</li>
              <li>The business or commercial purpose for collecting or selling your personal information.</li>
              <li>The categories of third parties with whom we share personal information.</li>
              <li>The specific pieces of personal information we have collected about you.</li>
              <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
              <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
            </ul>
            <p>Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.</p>

            <p className="font-semibold mt-4">(b) To delete your personal information.</p>
            <p>If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.</p>

            <p className="font-semibold mt-4">(c) To stop selling your personal information.</p>
            <p>We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a 'sale' under California law.</p>
            <p>If you submit a request to stop selling your personal information, we will stop making such transfers.</p>
            <p>Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.</p>
            <p>To exercise your California data protection rights described above, please send your request(s) by one of the following means:</p>
            <p>By email: <a href="mailto:farcast93@gmail.com" className="text-[#ff6b4e] hover:underline">farcast93@gmail.com</a></p>
            <p>Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.</p>
          </Section>

          <Section title="12. Service Providers">
            <p>We may employ third party companies and individuals to facilitate our Service ('Service Providers'), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
            <p>We reserve the right to update or change our Privacy Policy at any time, and we will notify you of any changes by posting the new Privacy Policy on our website. Your continued use of the service after we post any modifications to the Privacy Policy will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.</p>
            <p>If you have any questions about this Privacy Policy or want to exercise your data rights, please contact us at{" "}
              <a href="mailto:farcast93@gmail.com" className="text-[#ff6b4e] hover:underline">farcast93@gmail.com</a>.
            </p>
          </Section>
        </div>
      </div>

      <Footer />
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-bold text-[#1a1a2e]">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}
